name: CI

on:
  deployment:
    branches:
      - travis

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'
    - run: |
         mkdir deploy
         cd deploy/
         git clone https://github.com/xMrVizzy/MC-Texture-Changes.git .
         cd ../
    - run: python projectx.py
