name: Compare versions

on:
  schedule:
  - cron: 0 0/8 * * *
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Setup
        run: |
          python -m pip install requests

      - name: Run
        run: |
          python compare.py release 2
          python compare.py snapshot 2

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update for new Minecraft versions"
          branch: ${{ github.ref }}
