name: Compare versions

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Setup and run
        run: |
          python -m pip install requests
          python compare.py release 3
          python compare.py snapshot 3

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update for new Minecraft versions"
          branch: ${{ github.ref }}